### PR TITLE
Adding tests using jest

### PR DESCRIPTION
**Pull request by enoqueJonas**
# Functions and tests

## This PR was raised to:
- Create tests for functions 

## What does this PR do:
- Create test for the addTodo function
- Create test for the deleteTodo function

## Description of the task to be completed 
- Improve how the DOM is manipulated when calling of addTodo and deleteTodo

### CODE REVIEW

**Review by jerryowusu — COMMENTED** [review]
Hi @enoqueJonas 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

invalid


#### You have submitted a pair programming project which is supposed to be done by all members in your group. Kindly note that to move forward your project must have commits from all members of your pair programming group and not just one person.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by enniopo** [comment]
hi @enoqueJonas please submit another review request. The status of the activity has been manually changed in your dashboard. Thanks and sorry for the inconvenience

**Comment by enoqueJonas** [comment]
Greetings,On my dashboard, the activity changed from “Request Review” to “Submit”, so I submit the project without reading this email first because I thought It was approved. How can I ask for a re-review now?On 17/11/2022, at 20:11, Jerry Owusu ***@***.***> wrote:﻿
@jerryowusu commented on this pull request.

Hi @enoqueJonas
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
Invalid Code Review Request

You have submitted a pair programming project which is supposed to be done by all members in your group. Kindly note that to move forward your project must have commits from all members of your pair programming group and not just one person.
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.
Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

Invalid Code Review Request does not count into the code reviews limit.

**Comment by enoqueJonas** [comment]
Greetings @jerryowusu ,
On my dashboard, the activity changed from “Request Review” to “Submit”, so I submit the project without reading this email first because I thought It was approved. How can I ask for a re-review now?

**Comment by enoqueJonas** [comment]
Hi @enniopo, I worked with one of my coding partners in this project, my other partner is sick and is not able to contribute. The week is almost ending and we can not afford to wait for his contribution. Can I send the pull request for review?

**Comment by enoqueJonas** [comment]
Hi @enniopo <https://github.com/enniopo>, I worked with one of my coding
partners in this project, my other partner is sick and is not able to
contribute. The week is almost ending and we can not afford to wait for his
contribution. Can I send the pull request for review?

ennio ***@***.***> escreveu no dia quinta, 17/11/2022 à(s)
22:23:

**Review by alexpuente0 — APPROVED** [review]
Hi Team! 



Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Tests are really well done!
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
